import * as packages from './index';

const keys = Object.keys(packages).sort();
describe('"App" barrel package', () => {
  it('should export specific packages and interfaces', () => {
    expect(keys).toStrictEqual([
      'GuardArrayOptions',
      'GuardBigIntOptions',
      'GuardBooleanOptions',
      'GuardDateOptions',
      'GuardFloatOptions',
      'GuardFunctionOptions',
      'GuardIntegerOptions',
      'GuardJSONOptions',
      'GuardNumberOptions',
      'GuardObjectOptions',
      'GuardStringOptions',
      'ZeroDepError',
      'ZeroDepErrorFormat',
      'ZeroDepErrorGuard',
      'ZeroDepErrorGuardRange',
      'ZeroDepErrorGuardType',
      'ZeroDepErrorTo',
      'canIterate',
      'formatCurrency',
      'formatCurrencyCADen',
      'formatCurrencyCADfr',
      'formatCurrencyEURde',
      'formatCurrencyEURfr',
      'formatCurrencyGBP',
      'formatCurrencyHOF',
      'formatCurrencyUSD',
      'guardArray',
      'guardArrayHOF',
      'guardBigInt',
      'guardBigIntHOF',
      'guardBoolean',
      'guardBooleanHOF',
      'guardDate',
      'guardDateHOF',
      'guardFloat',
      'guardFloatHOF',
      'guardFunction',
      'guardFunctionHOF',
      'guardInteger',
      'guardIntegerHOF',
      'guardJSON',
      'guardJSONHOF',
      'guardNumber',
      'guardNumberHOF',
      'guardObject',
      'guardObjectHOF',
      'guardString',
      'guardStringHOF',
      'isArray',
      'isBigInt',
      'isBoolean',
      'isDate',
      'isError',
      'isFloat',
      'isFunction',
      'isInteger',
      'isJSON',
      'isMap',
      'isNil',
      'isNull',
      'isNumber',
      'isObject',
      'isPromise',
      'isRegex',
      'isSet',
      'isString',
      'isSymbol',
      'isTypedArray',
      'isUndefined',
      'isWeakMap',
      'isWeakSet',
      'localeGet',
      'localeSettings',
      'toJSON',
      'toJSONHOF',
      'toNumber',
      'toNumberHOF',
      'toString',
      'toStringHOF',
    ]);
  });

  // contrived test for barrel-file
  test.each(keys)('should have %s', (name) => {
    // @ts-ignore
    expect(['function', 'object', 'undefined']).toContain(typeof packages[name]);
  });
});
