version: 2
checks:
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 100
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
plugins:
  git-legal:
    enabled: true
exclude_patterns:
  - "**/*.eslintrc.json"
  - "**/*.spec.ts"
  - "**/.lib.swcrc"
  - "**/jest.config.ts"
  - "**/project.json"
  - "**/rollup.config.ts"
  - "**/tsconfig.json"
  - "**/tsconfig.lib.json"
  - "**/tsconfig.spec.json"
