export type StateUs =
  | 'Alabama'
  | 'Alaska'
  | 'American Samoa'
  | 'Arizona'
  | 'Arkansas'
  | 'Armed Forces Americas'
  | 'Armed Forces Europe'
  | 'Armed Forces Pacific'
  | 'California'
  | 'Colorado'
  | 'Connecticut'
  | 'Delaware'
  | 'District of Columbia'
  | 'Florida'
  | 'Georgia'
  | 'Guam'
  | 'Hawaii'
  | 'Idaho'
  | 'Illinois'
  | 'Indiana'
  | 'Iowa'
  | 'Kansas'
  | 'Kentucky'
  | 'Louisiana'
  | 'Maine'
  | 'Marshall Islands'
  | 'Maryland'
  | 'Massachusetts'
  | 'Michigan'
  | 'Micronesia'
  | 'Minnesota'
  | 'Mississippi'
  | 'Missouri'
  | 'Montana'
  | 'Nebraska'
  | 'Nevada'
  | 'New Hampshire'
  | 'New Jersey'
  | 'New Mexico'
  | 'New York'
  | 'North Carolina'
  | 'North Dakota'
  | 'Northern Mariana Islands'
  | 'Ohio'
  | 'Oklahoma'
  | 'Oregon'
  | 'Palau'
  | 'Pennsylvania'
  | 'Puerto Rico'
  | 'Rhode Island'
  | 'South Carolina'
  | 'South Dakota'
  | 'Tennessee'
  | 'Texas'
  | 'US Minor Outlying Islands'
  | 'US Virgin Islands'
  | 'Utah'
  | 'Vermont'
  | 'Virginia'
  | 'Washington'
  | 'West Virginia'
  | 'Wisconsin'
  | 'Wyoming';
